version: '2'
services:
  webhost:
    image: wavy-bird:latest
    # image: registry.devtoolbelt.xyz/wavy-bird:latest
    restart: always
    ports:
      - 4001:4000
    environment:
      PHX_HOST: "devtoolbelt.xyz"
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      RELEASE_COOKIE: ${RELEASE_COOKIE}